;<?php die(); /*
;
; DO NOT be tempted to edit this file, it doesn't do what you think.
; create a new file named prefs.local.ini.php and put your custom settings there

; main prefs
archive_dateformat               = "%b %d, %I:%M %p"
comments_are_ol                  = "1"
comments_auto_append             = "1"
comments_dateformat              = "%b %d, %I:%M %p"
comments_default_invite          = "Comment"
comments_disabled_after          = "42"
comments_disallow_images         = "0"
comments_mode                    = "0"
comments_moderate                = "1"
comments_on_default              = "0"
comments_sendmail                = "0"
dateformat                       = "since"
is_dst                           = "0"
logging                          = "all"
markup_default                   = "txptextile"
permlink_mode                    = "messy"
production_status                = "testing"
sitename                         = "my_site"
siteurl                          = ""
site_slogan                      = "my_slogan"
use_comments                     = "1"

; advanced prefs
admin_side_plugins               = "1"
allow_article_php_scripting      = "1"
allow_form_override              = "1"
allow_page_php_scripting         = "1"
allow_raw_php_scripting          = "0"
articles_use_excerpts            = "1"
attach_titles_to_permalinks      = "1"
comments_require_email           = "1"
comments_require_name            = "1"
comments_use_fat_textile         = "0"
comment_means_site_updated       = "1"
comment_nofollow                 = "1"
custom_10_set                    = ""
custom_1_set                     = "custom1"
custom_2_set                     = "custom2"
custom_3_set                     = ""
custom_4_set                     = ""
custom_5_set                     = ""
custom_6_set                     = ""
custom_7_set                     = ""
custom_8_set                     = ""
custom_9_set                     = ""
edit_raw_css_by_default          = "1"
elements_main                    = "elements.ini.php"
elements_aux                     = "pro/elements.ini.php"
expire_logs_after                = "7"
file_base_path                   = "files"
file_max_upload_size             = "2000000"
img_dir                          = "images"
include_email_atom               = "1"
max_url_len                      = "200"
never_display_email              = "0"
override_emailcharset            = "0"
permalink_title_format           = "1"
ping_textpattern_com             = "0"
ping_weblogsdotcom               = "0"
plugin_cache_dir                 = ""
publish_expired_articles         = "0"
rss_how_many                     = "5"
send_lastmod                     = "0"
show_comment_count_in_feed       = "1"
spam_blacklists                  = "sbl.spamhaus.org"
syndicate_body_or_excerpt        = "1"
tempdir                          = "tmp"

thumb_w                          = "100"
thumb_h                          = "100"
thumb_crop                       = "1"
use_dns                          = "1"
use_mail_on_feeds_id             = "0"
use_plugins                      = "1"

; */ ?>